a = int(input("Write how many cups of coffee you will need:\n"))
print("For", a, "cups of coffee you will need:")
print(a * 200, "ml of water")
print(a * 50, "ml of milk")
print(a * 15, "g of coffee beans")